name: Deploy to WP Engine Production
on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install theme assets
      run: npm install
      working-directory: wp-content/themes/falcon-tailwind-theme-starter

    - name: build theme assets
      run: npm run production
      working-directory: wp-content/themes/falcon-tailwind-theme-starter

    - name: delete node modules
      run: rm -Rf node_modules
      working-directory: wp-content/themes/falcon-tailwind-theme-starter 
      
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY }}
        WPE_ENV: falconstarter
        PHP_LINT: TRUE
        CACHE_CLEAR: TRUE